* Pam Expander Connections

The NEW Pam expander connector style was changed in the PRO due to various issues including;

+ It was the same connector type as the power header. Plugging power
  onto the expander connector would fry the module and cause
  irepairable damage.
+ Connector was non keyed causing confusion.
+ Connector was non latching (easily came loose).
+ Large size.

The signals are however basically the same. We hoped to produce an
adaptor cable so older expanders could still be used but for various
reasons this proved very difficult and didn't happen :(.

Presented here are the basic connector specs so one can DIY a cable (at OWN risk!).

** Connector Pins Outs

Looking at either module from the rear then pin signals are top to bottom as follows; 

*Pam NEW*

#+BEGIN_SRC
o +5V
o RUN
o CLOCK
o DATA
o GND

#+END_SRC

(This is a 'Dupont' style connector with 2.54mm pitch.)

*Pam PRO*

#+BEGIN_SRC
o GND
o RUN
o DATA
o CLOCK
o +5V

#+END_SRC

(This is a ZH 'JST Micro Connector' with 1.5mm pitch.)

All non power signals are 3v max. They need buffering and level
shifting (expanders do this) or otherwise they can damage Pam.

*PLEASE NOTE EVERYTHING IS PROVIDED AS IS. WE ARE UNABLE PROVIDE ANY SUPPORT TO ANYONE ATTEMPTING TO USE THIS INFORMATION. DIY-ING A CABLE OR ATTEMPTING TO CONNECT TO ANYTHING OTHER THAN AN OFFICIAL ALM PAM
EXPANDER WILL INVALIDATE YORU WARRANTY!*


